# Generated by Django 5.0.6 on 2024-10-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Commodity", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="online_user",
            name="annual_income",
        ),
        migrations.RemoveField(
            model_name="online_user",
            name="identity_card",
        ),
        migrations.RemoveField(
            model_name="online_user",
            name="is_frozen",
        ),
        migrations.RemoveField(
            model_name="online_user",
            name="is_lost",
        ),
        migrations.RemoveField(
            model_name="online_user",
            name="property_valuation",
        ),
        migrations.RemoveField(
            model_name="online_user",
            name="service_year",
        ),
        migrations.AddField(
            model_name="online_user",
            name="email",
            field=models.CharField(default="Unknown", max_length=20),
        ),
    ]
