# Generated by Django 5.0.6 on 2024-10-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Commodity", "0002_remove_online_user_annual_income_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="online_user",
            name="email",
            field=models.CharField(default="Unknown", max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="online_user",
            name="password",
            field=models.CharField(default="Unknown", max_length=30),
        ),
        migrations.AlterField(
            model_name="online_user",
            name="phone_num",
            field=models.CharField(default="Unknown", max_length=30),
        ),
        migrations.AlterField(
            model_name="online_user",
            name="user_name",
            field=models.CharField(default="Unknown", max_length=30, unique=True),
        ),
    ]
