# Generated by Django 5.0.6 on 2024-11-19 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "Commodity",
            "0003_alter_online_user_email_alter_online_user_password_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Favorite",
            fields=[
                ("favorite_id", models.AutoField(primary_key=True, serialize=False)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="OnlineUser",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(max_length=30, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_num", models.CharField(max_length=15)),
                ("is_blacklisted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Platform",
            fields=[
                ("platform_id", models.AutoField(primary_key=True, serialize=False)),
                ("platform_name", models.CharField(max_length=50, unique=True)),
                ("website_url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="PriceAlert",
            fields=[
                ("alert_id", models.AutoField(primary_key=True, serialize=False)),
                ("target_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_alerts",
                        to="Commodity.onlineuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                ("record_id", models.AutoField(primary_key=True, serialize=False)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="Commodity.platform",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("category", models.CharField(max_length=50, null=True)),
                ("image_url", models.URLField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="online_user",
        ),
        migrations.AddField(
            model_name="favorite",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorites",
                to="Commodity.onlineuser",
            ),
        ),
        migrations.AddField(
            model_name="pricehistory",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_history",
                to="Commodity.product",
            ),
        ),
        migrations.AddField(
            model_name="pricealert",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="Commodity.product",
            ),
        ),
        migrations.AddField(
            model_name="favorite",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorited_by",
                to="Commodity.product",
            ),
        ),
    ]
