# Generated by Django 5.0.6 on 2024-12-21 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "Commodity",
            "0004_favorite_onlineuser_platform_pricealert_pricehistory_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="favorite",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="favorite",
            name="platform",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorites",
                to="Commodity.platform",
            ),
        ),
        migrations.AddField(
            model_name="favorite",
            name="price_at_favorite",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="onlineuser",
            name="role",
            field=models.CharField(default="user", max_length=20),
            preserve_default=False,
        ),
    ]
