# Generated by Django 5.0.6 on 2024-12-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Commodity", "0005_favorite_note_favorite_platform_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="link",
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
