# Generated by Django 5.0.6 on 2024-12-22 05:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Commodity", "0006_product_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="favorite",
            name="link",
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
