# Generated by Django 5.0.6 on 2024-10-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="online_user",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "user_name",
                    models.CharField(default="Unknown", max_length=20, unique=True),
                ),
                ("password", models.CharField(default="Unknown", max_length=20)),
                ("identity_card", models.CharField(max_length=18, unique=True)),
                ("phone_num", models.CharField(default="Unknown", max_length=20)),
                ("annual_income", models.FloatField(null=True)),
                ("property_valuation", models.FloatField(null=True)),
                ("service_year", models.IntegerField(null=True)),
                ("is_frozen", models.BooleanField(default=False)),
                ("is_lost", models.BooleanField(default=False)),
                ("is_blacklisted", models.BooleanField(default=False)),
            ],
        ),
    ]
